#!/usr/bin/env python3

import subprocess

subprocess.run(["brew", "install", "asdf"])

plugins = {
  "cabal": {
    "git_url": "https://github.com/sestrella/asdf-ghcup.git",
    "dependencies": ["ghcup"]
  },
  "ghc": {
    "git_url": "https://github.com/sestrella/asdf-ghcup.git",
    "dependencies": ["ghcup"]
  },
  "nodejs": {
    "git_url": None,
    "dependencies": []
  },
  "python": {
    "git_url": None,
    # https://github.com/pyenv/pyenv/wiki#suggested-build-environment
    "dependencies": ["openssl", "readline", "sqlite3", "xz", "zlib", "tcl-tk"]
  },
  "ruby": {
    "git_url": None,
    # https://github.com/rbenv/ruby-build/wiki#suggested-build-environment
    "dependencies": ["openssl@1.1", "readline", "libyaml"]
  },
  "rust": {
    "git_url": None,
    "dependencies": []
  },
  "stack": {
    "git_url": None,
    "dependencies": []
  }
}

for name, plugin in plugins.items():
  git_url = plugin["git_url"]
  if git_url is None:
    subprocess.run(["asdf", "plugin", "add", name])
  else:
    subprocess.run(["asdf", "plugin", "add", name, git_url])

  dependencies = plugin["dependencies"]
  if dependencies:
    subprocess.run(["brew", "install"] + dependencies)
