#!/bin/bash

vim_plug="$HOME/.local/share/nvim/site/autoload/plug.vim"

if [[ -e $vim_plug ]]; then
  nvim +PlugUpdate +qa
else
  curl -fLo $vim_plug --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
