call plug#begin('~/.vim/plugged')

Plug 'altercation/vim-colors-solarized'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-projectionist'
Plug 'valloric/youcompleteme'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'w0rp/ale'

" HTML
Plug 'mattn/emmet-vim'

" Ruby
Plug 'tpope/vim-rails'

call plug#end()

set number

set expandtab
set shiftwidth=2
set tabstop=2

set nobackup
set noswapfile
set noundofile

set splitbelow
set splitright

set colorcolumn=80
