(source gnu)
(source melpa)

(development
 (depends-on "color-theme-solarized")
 (depends-on "company")
 (depends-on "evil")
 (depends-on "evil-leader")
 (depends-on "fiplr")
 (depends-on "grizzl")
 (depends-on "neotree")
 (depends-on "projectile")
 (depends-on "tide"))
