(source gnu)
(source melpa)

(development
 (depends-on "color-theme-solarized")
 (depends-on "evil")
 (depends-on "evil-leader")
 (depends-on "intero")
 (depends-on "my-site-start" :git "https://github.com/tripleee/my-site-start.git")
 (depends-on "neotree")
 (depends-on "tide"))
