return require("packer").startup(function(use)
  use("wbthomason/packer.nvim")

  use("cormacrelf/dark-notify")
  use("hrsh7th/cmp-nvim-lsp")
  use("hrsh7th/cmp-vsnip")
  use("hrsh7th/nvim-cmp")
  use("hrsh7th/vim-vsnip")
  use("ishan9299/nvim-solarized-lua")
  use("neovim/nvim-lspconfig")
  use("nvim-lua/plenary.nvim")
  use("nvim-telescope/telescope.nvim")
  use("nvim-treesitter/nvim-treesitter")
  use("nvim-treesitter/nvim-treesitter-textobjects")
end)
