#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

if [ ! -d ~/.local/share/nvim/site/pack/packer/start/packer.nvim ]; then
  echo "Cloning packer.nvim"
  git clone --depth 1 https://github.com/wbthomason/packer.nvim \
    ~/.local/share/nvim/site/pack/packer/start/packer.nvim
else
  echo "packer.nvim already exists"
fi

# https://github.com/wbthomason/packer.nvim#bootstrapping
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
