#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

git_clone() {
  if [ -d $2 ]; then
    echo "$2 already exists"
  else
    echo "Installing $2"
    git clone $1 $2
  fi
}

git_clone "--depth 1 https://github.com/wbthomason/packer.nvim" ~/.local/share/nvim/site/pack/packer/start/packer.nvim
git_clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
